name: stream_chat_localizations
description: The Official localizations for Stream Chat Flutter, a service for building chat applications
version: 4.0.0
homepage: https://github.com/GetStream/stream-chat-flutter
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stream_chat_flutter:
    git:
      url: https://github.com/soarity/stream-chat-flutter.git
      ref: wer6/release/5.3.0
      path: packages/stream_chat_flutter

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
