name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 5.3.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

publish_to: "none"

dependencies:
  cached_network_image: ^3.2.3
  chewie: ^1.3.4
  collection: ^1.16.0
  contextmenu: ^3.0.0
  desktop_drop: ^0.4.0
  diacritic: ^0.1.3
  dio: ^4.0.6
  ezanimation: ^0.6.0
  file_picker: ^5.2.4
  file_selector: ^0.9.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  flutter_portal: ^1.1.0
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.1+1
  http: ^0.13.4
  http_parser: ^4.0.1
  image_gallery_saver: ^1.7.0
  image_picker: ^0.8.6
  jiffy: ^5.0.0
  lottie: ^2.0.0
  meta: ^1.3.0
  path_provider: ^2.0.10
  photo_manager: ^2.5.2
  photo_view: ^0.14.0
  rxdart: ^0.27.0
  share_plus: ^6.2.0
  shimmer: ^2.0.0
  stream_chat_flutter_core:
    git:
      url: https://github.com/soarity/stream-chat-flutter.git
      ref: wer6/release/5.7.0
      path: packages/stream_chat_flutter_core
  synchronized: ^3.0.0
  thumblr: ^0.0.4
  url_launcher: ^6.1.9
  video_player: ^2.4.8
  video_thumbnail: ^0.5.3

flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/
  uses-material-design: true

dev_dependencies:
  dart_code_metrics: ^4.4.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0
  path: ^1.8.0
